name: CD

on:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
  workflow_dispatch:

jobs:
  deploy:
    name: Release
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Publish Features
        uses: devcontainers/action@2858bb873d82d653b033bfe0977fb8a16708b0c3 # v1
        with:
          publish-features: true
          base-path-to-features: ./src
          generate-docs: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR for Documentation
        run: |
          set -e
          echo "Start."
          # Configure git and Push updates
          git config --global user.email github-actions@github.com
          git config --global user.name github-actions
          git config pull.rebase false
          branch="automated-documentation-update-$GITHUB_RUN_ID"
          git checkout -b "$branch"
          message='docs: automated update'
          # Add / update and commit
          git add -- */**/README.md
          git commit -m "$message" || export NO_UPDATES=true
          # Push
          if [ "$NO_UPDATES" != "true" ] ; then
              git push origin "$branch"
              gh pr create --title "$message" --body "$message"
              gh pr merge --auto --squash --delete-branch
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
