name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@89504f15e51cfdb0ca91e07bad599eca5b861a7d # 1.3.22

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@528049dce833673f136ddfc09c2720d450029a6b # v1.4.2
        with:
          validate-only: true
          base-path-to-features: ./src
