name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@fdbf26a2c9512b5e617ae65fa77a3f92c1598a56 # 1.3.21

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@528049dce833673f136ddfc09c2720d450029a6b # v1.4.2
        with:
          validate-only: true
          base-path-to-features: ./src
