name: CI

on:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
  pull_request:
    paths:
      - src/**
      - test/**
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@3f8cae6bc8e5ef6d58062d7c5cc471d81e8ded05 # v1
        with:
          validate-only: true
          base-path-to-features: ./src
