name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@07ebbc2697c1505689d0c8fab407f3f18b325788 # 1.3.15

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@2858bb873d82d653b033bfe0977fb8a16708b0c3 # v1.4.1
        with:
          validate-only: true
          base-path-to-features: ./src
