name: CI

on:
  pull_request:
    branches: [main]
  workflow_call:
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run pre-commit
        uses: nikaro/actions/pre-commit@034b5e995ae7de67fb5f813951e3678085f7d129 # 1.6.3

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@528049dce833673f136ddfc09c2720d450029a6b # v1.4.2
        with:
          validate-only: true
          base-path-to-features: ./src
