name: CI

on:
  push:
    branches: [main]
    paths:
      - src/**
      - test/**
  pull_request:
    paths:
      - src/**
      - test/**
  workflow_dispatch:

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Validate devcontainer-feature.json files
        uses: devcontainers/action@2858bb873d82d653b033bfe0977fb8a16708b0c3 # v1
        with:
          validate-only: true
          base-path-to-features: ./src
